/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import com.google.gson.Gson;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;

public class App {
    public static Quote[] getQuotes(String filePathToJSON) throws IOException {
        Gson gson = new Gson();
        String quoteFile = new String(Files.readAllBytes(Paths.get(filePathToJSON)));
        Quote[] quotes = gson.fromJson(quoteFile, Quote[].class);
        return quotes;
    }

    public static Quote getRandomQuote(Quote[] quotes) {
        int randomIndex = (int)(Math.random() * quotes.length);
        return quotes[randomIndex];
    }

    public static Quote getQuoteByAuthor(Quote[] quotes, String author) {
        for (int i = 0; i < quotes.length; i++) {
            if (quotes[i].author.equals(author)) {
                return quotes[i];
            }
        }

        return new Quote();
    }

    public static Quote getQuoteBySearchWord(Quote[] quotes, String word) throws NoSuchMethodException {
        for (int i = 0; i < quotes.length; i++) {
            if (quotes[i].text.contains(word)) {
                return quotes[i];
            }
        }

        throw new NoSuchMethodException("word was not found for all available quotes");
    }

    public static void main(String[] args) throws IOException {
        String command = args[0];
        String searchWord = args[1];
        Quote[] listOfQuotes = getQuotes("src/main/resources/recentquotes.json");
        Quote randomQuote = getRandomQuote(listOfQuotes);
        System.out.println(randomQuote.toString());
    }
}
